#include "wii_device.h"
#include "godot_cpp/core/class_db.hpp"

using namespace godot;

WiiDevice::WiiDevice() {
}

WiiDevice::~WiiDevice() {
}

void WiiDevice::_bind_methods() {
	BIND_ENUM_CONSTANT(INTERFACE_CORE);
	BIND_ENUM_CONSTANT(INTERFACE_ACCEL);
	BIND_ENUM_CONSTANT(INTERFACE_IR);
	BIND_ENUM_CONSTANT(INTERFACE_MOTION_PLUS);
	BIND_ENUM_CONSTANT(INTERFACE_NUNCHUK);
	BIND_ENUM_CONSTANT(INTERFACE_CLASSIC_CONTROLLER);
	BIND_ENUM_CONSTANT(INTERFACE_BALANCE_BOARD);
	BIND_ENUM_CONSTANT(INTERFACE_PRO_CONTROLLER);
	BIND_ENUM_CONSTANT(INTERFACE_DRUMS);
	BIND_ENUM_CONSTANT(INTERFACE_GUITAR);
}

void WiiDevice::poll() {
}